### ISSUE TITLE
如何忽略某些js、ts文件不进行remove

### ISSUE THREAD

**Issue by zhl154381001** [dishait/vite-plugin-removelog#1]

**Comment by markthree** [comment]
@zhl154381001 未提供对应特性，欢迎 `pr`

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，已支持 👉 [v0.1.0](https://github.com/dishait/vite-plugin-removelog/releases/tag/v0.1.0)

**Comment by zhl154381001** [comment]
| |
heling.zhang
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月1日 18:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [dishait/vite-plugin-removelog] 如何忽略某些js、ts文件不进行remove (Issue #1) |

@zhl154381001 靓仔你好，已支持 👉v0.1.0
